References
----------
.. [CIT1] \A. Dubey, A. Bose, M. Liu and L. N. Ochoa, "Paving the Way for Advanced Distribution Management Systems Applications: Making the Most of Models and Data," in *IEEE Power and Energy Magazine*, vol. 18, no. 1, pp. 63-75, Jan.-Feb. 2020
.. [CIT2] \S. Poudel, A. Dubey and K. P. Schneider, "A Generalized Framework for Service Restoration in a Resilient Power Distribution System," *Submitted to IEEE Systems Journal (Under Revision)*
.. [CIT3] \S. Poudel and A. Dubey, "Critical Load Restoration Using Distributed Energy Resources for Resilient Power Distribution System," *in IEEE Transactions on Power Systems*, vol. 34, no. 1, pp. 52-63, Jan. 2019.
.. [CIT4] \S. Poudel, A. Dubey and A. Bose, "Risk-Based Probabilistic Quantification of Power Distribution System Operational Resilience," *in IEEE Systems Journal*, doi: 10.1109/JSYST.2019.2940939.
.. [CIT5] \S. Poudel and A. Dubey, "A Graph-theoretic Framework for Electric Power Distribution System Service Restoration," *2018 IEEE Power & Energy Society General Meeting (PESGM)*, Portland, OR, 2018, pp. 1-5.
.. [CIT6] \S. Poudel, A. Dubey, P. Sharma, and K. P. Schneider, "A Standalone FLISR Application Using GridAPPS-D -- Standards-Based Open-Source ADMS Platform," *in prep for IEEE Power and Energy Technology Systems Journal*
.. [CIT7] \S. Poudel, A. Dubey, and A. Bose, "Probabilistic Quantification of Power Distribution System Operational Resilience," *2019 IEEE Power & Energy Society General Meeting (PESGM)*, Atlanta, GA, 2019, pp. 1-5
.. [CIT8] \S. Poudel, M. Mukherjee and A. Dubey, "Optimal Positioning of Mobile Emergency Resources for Resilient Restoration," *2018 North American Power Symposium (NAPS)*, Fargo, ND, 2018, pp. 1-6.
.. [CIT9] \W. H. Kersting, "Radial distribution test feeders," in *2001 IEEE Power Engineering Society Winter Meeting. Conference Proceedings (Cat. No.01CH37194)*, 2001, pp. 908-912 vol.2.
.. [CIT10] \R. F. Arritt and R. C. Dugan, "The IEEE 8500-node test feeder," in *IEEE PES T&D 2010*, pp. 1-6.

	
